---
- name: Adds vbernat PPA
  apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy_major_minor }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and haproxy_major_minor is defined

- name: Adds PPA pinning to prevent upgrading to distribution version
  template:
    src: vbernat-haproxy-X.Y-pin-1000
    dest: /etc/apt/preferences.d/vbernat-haproxy-{{ haproxy_major_minor | regex_replace('\.', '_') }}-pin-1000
  when: ansible_distribution == "Ubuntu" and haproxy_major_minor is defined

- name: Installs haproxy (specific version)
  apt:
    pkg: "haproxy={{ haproxy_major_minor }}.*"
    state: present
  register: __haproxy_installed
  when: haproxy_major_minor is defined

- name: Installs haproxy (OS default version)
  apt:
    pkg: "haproxy"
    state: present
  register: __haproxy_installed
  when: haproxy_major_minor is not defined

- name: Installs socat
  apt:
    pkg: socat
    state: latest

- name: Adds main config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy
  tags:
    - config
    - haproxy:config

- name: Creates config fragments directory
  file:
    path: /etc/haproxy/conf.d
    state: directory
  notify: Restart haproxy

- name: Adds system defaults
  template:
    src: defaults.j2
    dest: /etc/default/haproxy
  notify: Restart haproxy
  tags:
    - config
    - haproxy:config

- name: Checks if renewal hook directory exists
  stat:
    path: /etc/letsencrypt/renewal-hooks/post
  register: __le_hook_stat
  

- name: Adds renews script is directory exists
  copy:
    content: |
      #!/bin/bash
      systemctl reload haproxy
    dest: /etc/letsencrypt/renewal-hooks/post/10-haproxy.sh
  when: __le_hook_stat.stat.isdir is defined and __le_hook_stat.stat.isdir
