- include_tasks: check_vars.yml
  tags:
    - haproxy
    - check

- include_tasks: haproxy.yml
  tags:
    - haproxy

- include_tasks: letsencrypt.yml
  when: haproxy_letsencrypt_manage
  tags:
    - haproxy
    - letsencrypt

