
---
- include_tasks:
    file: check_vars.yml
    apply:
      tags:
        - check
        - haproxy
  tags:
    - always

- include_tasks:
    file: haproxy.yml
    apply:
      tags:
        - haproxy
  tags:
    - always

- include_tasks:
    file: letsencrypt-lua.yml
    apply:
      tags:
        - haproxy
        - letsencrypt
  tags:
    - always
  when: haproxy_letsencrypt_manage
