
---
- name: Include check_vars
  include_tasks:
    file: check_vars.yml
    apply:
      tags:
        - check
        - haproxy
  tags:
    - always

- name: Include haproxy
  include_tasks:
    file: haproxy.yml
    apply:
      tags:
        - haproxy
  tags:
    - always

- name: Include letsencrypt-lua
  include_tasks:
    file: letsencrypt-lua.yml
    apply:
      tags:
        - haproxy
        - letsencrypt
  tags:
    - always
  when: haproxy_letsencrypt_manage
